In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Week1_GA_dataset.csv to Week1_GA_dataset.csv

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("Week1_GA_dataset.csv")

In [ ]:
df

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,?,Detached House,3,2,1092.0,1.025953,East
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2022-09-30,2022,Bridgeport,153660.0,322000.0,?,Detached House,3,3,917.0,1.003979,North
9996,2022-09-30,2022,Bridgeport,109820.0,340000.0,?,Duplex,4,4,1416.0,1.003979,North
9997,2022-09-30,2022,Waterbury,83210.0,170000.0,Single Family,Detached House,3,1,964.0,1.003979,South
9998,2022-09-30,2022,NaN,216420.0,415000.0,Single Family,Detached House,3,3,1014.0,1.003979,North
9999,2022-09-30,2022,Norwalk,154920.0,196000.0,Single Family,Detached House,3,1,932.0,1.003979,East

# Question 1:
* Select all the even indexed rows from the given dataset. What is the value in the 3rd indexed column of the 0th indexed row in the selected dataframe. (row/ column indexed from zero(0) in python/pandas)

In [ ]:
even_df = df.iloc[list(range(0, 10000, 2))]
even_df

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,?,Detached House,3,2,1092.0,1.025953,East
6,2009-01-02,2009,Norwalk,571060.0,1000000.0,Single Family,Detached House,3,2,NaN,1.025953,South
8,2009-01-02,2009,NaN,603540.0,1680000.0,Single Family,Detached House,3,1,1039.0,1.025953,East
...,...,...,...,...,...,...,...,...,...,...,...,...
9990,2022-09-30,2022,NaN,352030.0,700000.0,?,Detached House,3,3,958.0,1.003979,North
9992,2022-09-30,2022,Fairfield,NaN,680000.0,Single Family,Detached House,3,2,908.0,1.003979,West
9994,2022-09-30,2022,NaN,155550.0,215000.0,Three Family,Triplex,6,5,2114.0,1.003979,North
9996,2022-09-30,2022,Bridgeport,109820.0,340000.0,?,Duplex,4,4,1416.0,1.003979,North
9998,2022-09-30,2022,NaN,216420.0,415000.0,Single Family,Detached House,3,3,1014.0,1.003979,North

In [ ]:
even_df.iloc[0, 3]

np.float64(111440.0)

# Question 2
* Select all the even indexed rows from the given dataset. What is the value in the 3rd indexed column of the 332th indexed row in the selected dataframe. (row/ column indexed from zero(0))

In [ ]:
even_df.iloc[332, 3]

np.float64(256200.0)

# Question 3
* Select all the odd indexed rows from the given dataset. What is the value in the 3rd indexed column of the 332th indexed row in the selected dataframe. (row/ column indexed from zero(0))
* Please consider case sensitivity while giving your solution capital letter ≠ small letter
* If it is a string don't write quotes in the solution.

In [ ]:
odd_df = df.iloc[list(range(1, 10000, 2))]
odd_df

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
5,2009-01-02,2009,Greenwich,2868880.0,3300000.0,Single Family,Detached House,3,1,1039.0,1.025953,North
7,2009-01-02,2009,Greenwich,592760.0,920000.0,Single Family,Detached House,3,3,937.0,1.025953,North
9,2009-01-02,2009,Bridgeport,137901.0,245000.0,Single Family,Detached House,3,1,956.0,1.025953,West
...,...,...,...,...,...,...,...,...,...,...,...,...
9991,2022-09-30,2022,Norwalk,344270.0,512500.0,Single Family,Detached House,3,3,NaN,1.003979,West
9993,2022-09-30,2022,West Hartford,121870.0,235000.0,Single Family,Detached House,3,2,1087.0,1.003979,South
9995,2022-09-30,2022,Bridgeport,153660.0,322000.0,?,Detached House,3,3,917.0,1.003979,North
9997,2022-09-30,2022,Waterbury,83210.0,170000.0,Single Family,Detached House,3,1,964.0,1.003979,South
9999,2022-09-30,2022,Norwalk,154920.0,196000.0,Single Family,Detached House,3,1,932.0,1.003979,East

In [ ]:
odd_df.iloc[332, 3]

np.float64(352940.0)

# Question 4
* Select all the odd indexed columns from the given dataset. What is the value in the 5th indexed column of the 100th indexed row in the selected dataframe. (row/ column indexed from zero(0))
* Please consider case sensitivity while giving your solution capital letter ≠ small letter
* If it is a string don't write quotes in the solution.

In [ ]:
odd_col_df = df.iloc[:, list(range(1, 12, 2))]
odd_col_df

      Year  Estimated Value       Property  num_rooms  carpet_area   Face
0     2009         111440.0  Single Family          3        996.0  South
1     2009         124670.0     Two Family          4       1241.0  South
2     2009          55720.0  Single Family          3        910.0  South
3     2009        4775276.0  Single Family          3        971.0   East
4     2009         112351.0              ?          3       1092.0   East
...    ...              ...            ...        ...          ...    ...
9995  2022         153660.0              ?          3        917.0  North
9996  2022         109820.0              ?          4       1416.0  North
9997  2022          83210.0  Single Family          3        964.0  South
9998  2022         216420.0  Single Family          3       1014.0  North
9999  2022         154920.0  Single Family          3        932.0   East

[10000 rows x 6 columns]

In [ ]:
odd_col_df.iloc[100, 5]

'West'

# Question 5
* Select all the even indexed columns and even indexed rows from the given dataset. What is the value in the 3th indexed column of the 255th indexed row in the selected dataframe. (row/ column indexed/starts from zero(0))
* Please consider case sensitivity while giving your solution capital letter ≠ small letter
* If it is a string don't write quotes in the solution.

In [ ]:
new_df = df.iloc[list(range(0, 10000, 2)), list(range(0, 12, 2))]
new_df

,Date,Locality,Sale Price,Residential,num_bathrooms,property_tax_rate
0,2009-01-02,Waterbury,185000.0,Detached House,3,1.025953
2,2009-01-02,Waterbury,140000.0,Detached House,2,1.025953
4,2009-01-02,Bridgeport,210000.0,Detached House,2,1.025953
6,2009-01-02,Norwalk,1000000.0,Detached House,2,1.025953
8,2009-01-02,NaN,1680000.0,Detached House,1,1.025953
...,...,...,...,...,...,...
9990,2022-09-30,NaN,700000.0,Detached House,3,1.003979
9992,2022-09-30,Fairfield,680000.0,Detached House,2,1.003979
9994,2022-09-30,NaN,215000.0,Triplex,5,1.003979
9996,2022-09-30,Bridgeport,340000.0,Duplex,4,1.003979
9998,2022-09-30,NaN,415000.0,Detached House,3,1.003979

In [ ]:
new_df.iloc[255, 3]

'Detached House'

# Question 6
* Determine the number of samples (rows) in the dataset that belong to the six most recent years, based on the provided data.

In [ ]:
df["Year"].isin([2025, 2024, 2023, 2022, 2021, 2020]).sum()

np.int64(2442)

# Question 7
* Determine the number of samples (rows) in the dataset which has num_rooms = 3 and num_bathrooms = 3

In [ ]:
condition = (df["num_rooms"] == 3) & (df["num_bathrooms"] == 3)

df[condition]

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
7,2009-01-02,2009,Greenwich,592760.0,920000.0,Single Family,Detached House,3,3,937.0,1.025953,North
13,2009-01-03,2009,Greenwich,1046920.0,600000.0,Single Family,Detached House,3,3,1068.0,1.025953,South
16,2009-01-05,2009,Waterbury,74620.0,206500.0,Single Family,Detached House,3,3,966.0,1.025953,South
22,2009-01-08,2009,NaN,1260560.0,1895000.0,Single Family,Detached House,3,3,1005.0,1.025953,South
...,...,...,...,...,...,...,...,...,...,...,...,...
9989,2022-09-29,2022,Stamford,373530.0,485000.0,?,Detached House,3,3,1084.0,1.003979,South
9990,2022-09-30,2022,NaN,352030.0,700000.0,?,Detached House,3,3,958.0,1.003979,North
9991,2022-09-30,2022,Norwalk,344270.0,512500.0,Single Family,Detached House,3,3,NaN,1.003979,West
9995,2022-09-30,2022,Bridgeport,153660.0,322000.0,?,Detached House,3,3,917.0,1.003979,North
9998,2022-09-30,2022,NaN,216420.0,415000.0,Single Family,Detached House,3,3,1014.0,1.003979,North

# Question 8
* Determine the number of samples (rows) in the dataset which has num_rooms = 3 or num_bathrooms = 3

In [ ]:
condition = (df["num_rooms"] == 3) | (df["num_bathrooms"] == 3)

df[condition]

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,?,Detached House,3,2,1092.0,1.025953,East
...,...,...,...,...,...,...,...,...,...,...,...,...
9993,2022-09-30,2022,West Hartford,121870.0,235000.0,Single Family,Detached House,3,2,1087.0,1.003979,South
9995,2022-09-30,2022,Bridgeport,153660.0,322000.0,?,Detached House,3,3,917.0,1.003979,North
9997,2022-09-30,2022,Waterbury,83210.0,170000.0,Single Family,Detached House,3,1,964.0,1.003979,South
9998,2022-09-30,2022,NaN,216420.0,415000.0,Single Family,Detached House,3,3,1014.0,1.003979,North
9999,2022-09-30,2022,Norwalk,154920.0,196000.0,Single Family,Detached House,3,1,932.0,1.003979,East

# Question 9
* In the Year 2022, how many houses (rows) located in the Greenwich Locality have exactly num_room == 3, and facing towards either the North or East?

In [ ]:
condition = (df["Year"] == 2022) & (df["Locality"] == "Greenwich") & (df["num_rooms"] == 3) & ((df["Face"] == "North") | (df["Face"] == "East"))
df[condition].count()

Date                 42
Year                 42
Locality             42
Estimated Value      32
Sale Price           42
Property             42
Residential          42
num_rooms            42
num_bathrooms        42
carpet_area          37
property_tax_rate    42
Face                 42
dtype: int64

# Question 10
* Calculate the number of samples(rows) that correspond to the month of August across all the years.?

In [ ]:
df["Date"] = pd.to_datetime(df["Date"])
august_rows = df[df["Date"].dt.month == 8]

august_rows

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
500,2009-08-01,2009,Greenwich,919800.0,1275000.0,Single Family,Detached House,3,1,NaN,1.025953,North
501,2009-08-01,2009,Fairfield,417130.0,505000.0,Single Family,Detached House,3,3,1011.0,1.025953,South
502,2009-08-01,2009,Fairfield,NaN,420000.0,Single Family,Detached House,3,3,976.0,1.025953,East
503,2009-08-01,2009,Norwalk,257950.0,460000.0,Single Family,Detached House,3,3,966.0,1.025953,East
504,2009-08-01,2009,Norwalk,239330.0,400000.0,Single Family,Detached House,3,2,973.0,1.025953,South
...,...,...,...,...,...,...,...,...,...,...,...,...
9862,2022-08-31,2022,Bridgeport,123720.0,230000.0,Single Family,Detached House,3,1,1084.0,1.003979,North
9863,2022-08-31,2022,Stamford,438680.0,472500.0,Single Family,Detached House,3,1,NaN,1.003979,South
9864,2022-08-31,2022,NaN,57760.0,120000.0,?,Triplex,6,5,2156.0,1.003979,West
9865,2022-08-31,2022,Fairfield,314650.0,287000.0,Single Family,Detached House,3,3,1012.0,1.003979,West
9866,2022-08-31,2022,Stamford,347990.0,579000.0,Single Family,Detached House,3,1,NaN,1.003979,North

# Question 11
* According to the data which Locality have highest average Sale Price?

In [ ]:
new_df = df.iloc[:, [2, 4]]
new_df

        Locality  Sale Price
0      Waterbury    185000.0
1     Bridgeport    150000.0
2      Waterbury    140000.0
3     Bridgeport    272900.0
4     Bridgeport    210000.0
...          ...         ...
9995  Bridgeport    322000.0
9996  Bridgeport    340000.0
9997   Waterbury    170000.0
9998         NaN    415000.0
9999     Norwalk    196000.0

[10000 rows x 2 columns]

In [ ]:
new_df.groupby("Locality").mean()

                 Sale Price
Locality
Bridgeport     1.740953e+05
Fairfield      7.277225e+05
Greenwich      2.270224e+06
Norwalk        5.590959e+05
Stamford       6.305313e+05
Waterbury      1.062152e+05
West Hartford  3.385472e+05